# Generated by Django 5.1.1 on 2025-02-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_game_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='cookie_Score',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.score')),
            ],
            bases=('mainapp.score',),
        ),
    ]
