# Generated by Django 5.1.1 on 2025-02-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookieclicker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cookie_Score',
        ),
    ]
